server.port=8081

spring.datasource.url=jdbc:postgresql://neondb_owner:npg_mzC1yHx4AVQh@ep-holy-firefly-atqwl784-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE